=== Lazy converter of YouTube playlists into podcasts

The LinuxDays conference has produced a lot of video recordings of many interesting presentations. It would be nice if there was a service turning those recordings into audio-only podcasts which could then allow listeners to download and listen to them without internet connection.

The goal is to automate this without need to download and convert all the audio files in advance.

==== Goals 

* Investigate a way how to interact with the YouTube API to get a list of videos' metadata from a given playlist.
* Create a web service presenting these metadata in a form of an RSS/Atom feed. Each item should contain a linked audio file which would be generated on-the-fly when downloaded by user.
* Whenever a user tries to download a linked audio file, the app should download the MPEG-DASH audio from YouTube using https://ytdl-org.github.io/youtube-dl/index.html[youtube-dl] or anything similar, convert the downloaded file in order to be accepted by a common player (ie. change container from MPEG-DASH to regular MPEG using for instance FFmpeg) and stream it to the user.
* The converted audio files should be cached by the app. If there are two concurrent downloads of the same file, the pull from YouTube should be done only once. The cache should be configurable.

==== Required outputs

A standalone application configured by a simple config file. The app should be published under a free software license of your choice.

==== Point of contact

mailto:ondrej.caletka@cesnet.cz[Ondřej Caletka]